version: '3.8'

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
      - news-service
      - payment-service
    networks:
      - app-network
  user-service:
    build:
      context: ./UserService
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./UserService/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  news-service:
    build:
      context: ./NewsService  
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ./NewsService/.env
    networks:
      - app-network
  
  payment-service:
    build:
      context: ./PaymentService
    restart: always
    ports:
      - "8003:8003"
    env_file:
      - ./PaymentService/.env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: